items:
    post:
        productConfigurationInstance:
            - Optional:
                  constraints:
                      - Collection:
                            fields:
                                displayData:
                                    - NotBlank
                                configuration:
                                    - NotBlank
                                configuratorKey:
                                    - NotBlank
                                isComplete:
                                    - NotNull
                                    - Type:
                                          type: boolean
                                availableQuantity:
                                    - NotBlank
                                    - Type:
                                          type: numeric
                                prices:
                                    - Optional:
                                          constraints:
                                              - All:
                                                    constraints:
                                                        - Collection:
                                                              fields:
                                                                  priceTypeName:
                                                                      - NotBlank
                                                                  netAmount:
                                                                      - NotBlank
                                                                      - Type:
                                                                            type: numeric
                                                                      - GreaterThanOrEqual:
                                                                            value: 0
                                                                  grossAmount:
                                                                      - NotBlank
                                                                      - Type:
                                                                            type: numeric
                                                                      - GreaterThanOrEqual:
                                                                            value: 0
                                                                  currency:
                                                                      - Collection:
                                                                            fields:
                                                                                code:
                                                                                    - NotBlank
                                                                                name:
                                                                                    - NotBlank
                                                                                symbol:
                                                                                    - NotBlank
                                                                  volumePrices:
                                                                      - Optional:
                                                                            constraints:
                                                                                - All:
                                                                                      constraints:
                                                                                          - Collection:
                                                                                                fields:
                                                                                                    netAmount:
                                                                                                        - Type:
                                                                                                              type: numeric
                                                                                                        - GreaterThanOrEqual:
                                                                                                              value: 0
                                                                                                    grossAmount:
                                                                                                        - Type:
                                                                                                              type: numeric
                                                                                                        - GreaterThanOrEqual:
                                                                                                              value: 0
                                                                                                    quantity:
                                                                                                        - NotBlank
                                                                                                        - Type:
                                                                                                              type: numeric
guest-cart-items:
    post:
        productConfigurationInstance:
            - Optional:
                  constraints:
                      - Collection:
                            fields:
                                displayData:
                                    - NotBlank
                                configuration:
                                    - NotBlank
                                configuratorKey:
                                    - NotBlank
                                isComplete:
                                    - NotNull
                                    - Type:
                                          type: boolean
                                availableQuantity:
                                    - NotBlank
                                    - Type:
                                          type: numeric
                                prices:
                                    - Optional:
                                          constraints:
                                              - All:
                                                    constraints:
                                                        - Collection:
                                                              fields:
                                                                  priceTypeName:
                                                                      - NotBlank
                                                                  netAmount:
                                                                      - NotBlank
                                                                      - Type:
                                                                            type: numeric
                                                                      - GreaterThanOrEqual:
                                                                            value: 0
                                                                  grossAmount:
                                                                      - NotBlank
                                                                      - Type:
                                                                            type: numeric
                                                                      - GreaterThanOrEqual:
                                                                            value: 0
                                                                  currency:
                                                                      - Collection:
                                                                            fields:
                                                                                code:
                                                                                    - NotBlank
                                                                                name:
                                                                                    - NotBlank
                                                                                symbol:
                                                                                    - NotBlank
                                                                  volumePrices:
                                                                      - Optional:
                                                                            constraints:
                                                                                - All:
                                                                                      constraints:
                                                                                          - Collection:
                                                                                                fields:
                                                                                                    netAmount:
                                                                                                        - Type:
                                                                                                              type: numeric
                                                                                                        - GreaterThanOrEqual:
                                                                                                              value: 0
                                                                                                    grossAmount:
                                                                                                        - Type:
                                                                                                              type: numeric
                                                                                                        - GreaterThanOrEqual:
                                                                                                              value: 0
                                                                                                    quantity:
                                                                                                        - NotBlank
                                                                                                        - Type:
                                                                                                              type: numeric
